### ISSUE TITLE
Probes written to temporary file with static name

### ISSUE THREAD

**Issue by dparks1134** [wwood/finishm#34]
Hello,

I am trying to run multiple instances of FinishM in parallel. However, I believe the call to velveth fails in this case as it creates a statically named temporary file (/tmp/probes.ftq.gz):

<code>INFO bio-velvet 31/08 07:52:23: Running velveth: /srv/sw/finishm/0.0.3/lib/assembly/../../ext/src/velveth arg13/velvet 51  -fasta -short /tmp/probes.ftq.gz -short ../../seq_data/qc/arg13.qc.1.fq.gz ../../seq_data/qc/arg13.qc.2.fq.gz -create_binary</code>

My runs eventually fail with:
<code>ERROR finishm 31/08 00:37:48: Probe sequence #344 has changed - perhaps the wrong velvet assembly directory was specified, or a fresh assembly is required.</code>

Cheers,
Donovan

**Comment by dparks1134** [comment]
Actually, this doesn't seem to be the case. It was just a weird clipping error on my terminal. The probes do have unique names. Still not clear why the run is failing though.

**Comment by wwood** [comment]
potentially due to non-`ATGCN` characters in the probe names. Fixed in 0.0.4?

**Comment by dparks1134** [comment]
This indeed seems to be the issue. Cheers!
