### ISSUE TITLE
printing contigs can fail when the middle stretch of nodes is too short

### ISSUE THREAD

**Issue by wwood** [wwood/finishm#36]
reported by @fauziharoon

A `Bio::Velvet::Graph::OrientedNodeTrail::InsufficientLengthException` is thrown.

On luca its at `/srv/projects/share/FAUZI_to_BEN`

**Comment by wwood** [comment]
Now
```
/srv/projects/finishm/roundup/FAUZI_to_BEN/
```

**Comment by wwood** [comment]
Hey Fauzi,

Contrary to my first guess, I found that the difficulty here was that the coverage of that bin was too small for finishm. Also, at 900kb I'm guessing (perhaps wrongly), that the bin is incomplete? It isn't a good idea to run `roundup` on incomplete bins, as the basic assumption of finishm is that the starting genome is pretty much complete.

**Comment by wwood** [comment]
I've pushed a new version 0.0.7 to rubygems, so this problem shouldn't happen again.

Thanks again for the bug report.

**Comment by fauziharoon** [comment]
Thanks Ben!
