### ISSUE TITLE
Can't test finishm

### ISSUE THREAD

**Issue by cwzkevin** [wwood/finishm#38]
When installing finishm, I am using following commands:
$ use ruby1.9.3
$ export GEM_HOME=/local/projects-t2/M8910/software/.gem/
$ gem install finishm

After finishm 0.0.8 is installed:
$ use ruby1.9.3
$ finishm

And below is the error message:
/usr/local/packages/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:45:in `require': /local/projects-t2/M8910/software/.gem/gems/ds-0.0.6/lib/ds/trees/binary_heap.rb:12: syntax error, unexpected tLPAREN_ARG, expecting keyword_do_LAMBDA or tLAMBEG (SyntaxError)
                    -> (parent, child) { parent >= child }
                        ^
/local/projects-t2/M8910/software/.gem/gems/ds-0.0.6/lib/ds/trees/binary_heap.rb:12: syntax error, unexpected '}', expecting keyword_end
/local/projects-t2/M8910/software/.gem/gems/ds-0.0.6/lib/ds/trees/binary_heap.rb:107: syntax error, unexpected $end, expecting keyword_end
        from /usr/local/packages/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /local/projects-t2/M8910/software/.gem/gems/ds-0.0.6/lib/ds.rb:22:in `<top (required)>'
        from /usr/local/packages/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/packages/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /local/projects-t2/M8910/software/.gem/gems/finishm-0.0.8/lib/assembly/acyclic_connection_finder.rb:1:in `<top (required)>'
        from /usr/local/packages/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/packages/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /local/projects-t2/M8910/software/.gem/gems/finishm-0.0.8/lib/priner.rb:23:in `<top (required)>'
        from /usr/local/packages/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/packages/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /local/projects-t2/M8910/software/.gem/gems/finishm-0.0.8/bin/finishm:10:in `<top (required)>'
        from /local/projects-t2/M8910/software/.gem/bin/finishm:23:in `load'
        from /local/projects-t2/M8910/software/.gem/bin/finishm:23:in `<main>'

**Comment by wwood** [comment]
Hi,

Looks to me like finishm requires a newer ruby version, because the 'ds' library does - the `->` syntax wasn't in ruby 1.9, IIRC. Do you get the same thing with a newer version of Ruby?

thanks.
ben

**Comment by cwzkevin** [comment]
Thanks, wwood.

Here is what I did:
**1. Installed a stable version of Ruby-2.3.1**
 $ which ruby
/local/projects-t2/M8910/software/ruby-2.3.1/bin/ruby

**2. Did a gem update since the gem coming with Ruby-2.3.1 has some problem**
$ gem update --system

$ gem -v
2.6.6
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**3. next, when I try to install finishm**
 $ gem install finishm
Building native extensions.  This could take a while...
ERROR:  Error installing finishm:
        ERROR: Failed to build gem native extension.

    current directory: /local/projects-t2/M8910/software/.gem/gems/finishm-0.0.8/ext
/local/projects-t2/M8910/software/ruby-2.3.1/bin/ruby mkrf_conf.rb

current directory: /local/projects-t2/M8910/software/.gem/gems/finishm-0.0.8/ext
/local/projects-t2/M8910/software/ruby-2.3.1/bin/ruby -rubygems /local/projects-t2/M8910/software/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.4.2/bin/rake RUBYARCHDIR=/local/projects-t2/M8910/software/.gem/extensions/x86_64-linux/2.3.0-static/finishm-0.0.8 RUBYLIBDIR=/local/projects-t2/M8910/software/.gem/extensions/x86_64-linux/2.3.0-static/finishm-0.0.8
cd /local/projects-t2/M8910/software/.gem/gems/finishm-0.0.8/ext/src
rake aborted!
NameError: uninitialized constant Config
Did you mean?  RbConfig
/local/projects-t2/M8910/software/.gem/gems/finishm-0.0.8/ext/Rakefile:12:in `block (2 levels) in <top (required)>'
/local/projects-t2/M8910/software/.gem/gems/finishm-0.0.8/ext/Rakefile:10:in `block in <top (required)>'
Tasks: TOP => default => compile
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /local/projects-t2/M8910/software/.gem/gems/finishm-0.0.8 for inspection.
Results logged to /local/projects-t2/M8910/software/.gem/extensions/x86_64-linux/2.3.0-static/finishm-0.0.8/gem_make.out

**Comment by cwzkevin** [comment]
One more try on a different version of Ruby-2.2.5, got the **same** error.

$ ruby -v
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]
$ gem -v
2.4.5.1

The error code is exactly the same as above.

**Comment by wwood** [comment]
OK, thanks. This is a bug in finishm then (now your Ruby version is too new!). I don't have time right now but I'll get back to you next week. If you were super keen you could try it on Ruby 2.1 where it was originally developed. Thanks for the bug report.

**Comment by cwzkevin** [comment]
Thanks, wwood.

I installed Ruby-2.1.10, and finishm installed fine. However, when I try to run it, got below error.
$ finishm
/local/projects-t2/M8910/software/ruby-2.1.10/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bio-primer3 (LoadError)
        from /local/projects-t2/M8910/software/ruby-2.1.10/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /local/projects-t2/M8910/software/.gem/gems/finishm-0.0.8/lib/finishm/primers.rb:9:in `<top (required)>'
        from /local/projects-t2/M8910/software/ruby-2.1.10/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /local/projects-t2/M8910/software/ruby-2.1.10/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /local/projects-t2/M8910/software/.gem/gems/finishm-0.0.8/lib/priner.rb:54:in `<top (required)>'
        from /local/projects-t2/M8910/software/ruby-2.1.10/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /local/projects-t2/M8910/software/ruby-2.1.10/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /local/projects-t2/M8910/software/.gem/gems/finishm-0.0.8/bin/finishm:10:in `<top (required)>'
        from /local/projects-t2/M8910/software/.gem/bin/finishm:23:in `load'
        from /local/projects-t2/M8910/software/.gem/bin/finishm:23:in `<main>'

$ ruby -v
ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-linux]
$ gem -v
2.2.5

**Comment by wwood** [comment]
Hi again,

Seems you ran into a hack I was using. I've now released a new version (0.0.9) which should fix both of the issues you brought up here. Note that it requires Ruby 2.3. Please let me know if there is anything else, you've certainly help improve FinishM, thanks.

**Comment by cwzkevin** [comment]
Thanks for the update, wwood. I can try now.
