### ISSUE TITLE
'roundup' command with paired-end reads

### ISSUE THREAD

**Issue by minsookim1983** [wwood/finishm#40]
Hello,

Is it possible to do 'roundup' job with paired-end reads (forward & reverse reads)? In the Usage of 'roundup' job, I could not find any flags for paired-end reads. How about putting in two files one by one? Or, should I merge two reads into a single read? 
Thank you.

Min-Soo

**Comment by wwood** [comment]
Hi,
Currently FinishM only processes the reads as single-ended. You can put both the forward and reverse in individually and they will be treated as single ended reads.  Whether to merge or not depends on your data. If you have high enough coverage then there is probably little point and runs the risk of incorrect overlaps introducing errors, but you might be forced into it if you are only at low coverage.

**Comment by minsookim1983** [comment]
I processed 'roundup' job with two paired-end files. However, an error was popped up again.
I attached a file containing the error message. 
[roundup.errors.txt](https://github.com/wwood/finishm/files/461089/roundup.errors.txt)
It looks about lack of memory in my system. Is it right?
Thank you.

Min-Soo

**Comment by wwood** [comment]
I'm afraid you are correct, you are out of memory. We hope to move away from velvet for this reason in the future, but we aren't there yet. There are various options depending on your situations, the most straightforward of which is to supply finishm less reads.
